### ISSUE TITLE
Peer-to-Peer code Review 2/11

### ISSUE THREAD

**Issue by taher-software** [Qoosim/Todo-List#6]
# Highlight :+1: 
- Very structured and organized code.
- The application run smoothly.
# Changes: 
- Update you live demo to match the latest version.
- Generate html content with JavaScript code  to meet the requirement of the task.

**Comment by micheaol** [comment]
## **Hi @Qoosim ,** 

### **Nice job**

Good job so far! Your code looks fine, well structured, good job :+1:  :+1: 

There are some issues that you still need to work on, you are almost there!

## To highlight:
- Gitflow is used :clap:
- Good PR description :clap: 

## Required Changes ♻️ 
- [ ] _Update you live demo link in the README.md to display correct page.:_

**Comment by Qoosim** [comment]
Thanks to all for taking the time to review my code and giving me useful
feedback.
You are such great team members.

Kind regards.

**Comment by Qoosim** [comment]
Thank @micheaol and @Taher-web-dev.
Your suggestions have been taken care of.

I appreciate your suggestions.
